spring:
  mvc:
    log-request-details: true

logging:
  level:
    sun:
      rmi:
        transport:
          tcp: ERROR
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

coach-diff:
  default-summoner:
    name: ${DEFAULT_SUMMONER_NAME}
    tag: ${DEFAULT_SUMMONER_TAG}

riot:
  api:
    key: ${RIOT_API_KEY}
    base-url-accounts: https://europe.api.riotgames.com
    base-url-league: https://euw1.api.riotgames.com
    base-url-summoner: https://euw1.api.riotgames.com
  ddragon:
    version: ${DDRAGON_VERSION:16.3.1}
    base-url: https://ddragon.leagueoflegends.com/cdn